// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwswb55U_Nd515JcrEqVGj0ZJfSUrUxY',
    appId: '1:68816868203:web:66771e3dd622b4dafe322e',
    messagingSenderId: '68816868203',
    projectId: 'my-personal-tasks-bb04d',
    authDomain: 'my-personal-tasks-bb04d.firebaseapp.com',
    storageBucket: 'my-personal-tasks-bb04d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLczDdiVP-2B2KK3dhO2vVWaUTjvBe884',
    appId: '1:68816868203:android:ec3f3a3677d9af42fe322e',
    messagingSenderId: '68816868203',
    projectId: 'my-personal-tasks-bb04d',
    storageBucket: 'my-personal-tasks-bb04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSAag9piuKENZDa3aex5hfs3zpcYMRUE',
    appId: '1:68816868203:ios:3dd6a5a40be4598ffe322e',
    messagingSenderId: '68816868203',
    projectId: 'my-personal-tasks-bb04d',
    storageBucket: 'my-personal-tasks-bb04d.appspot.com',
    iosClientId: '68816868203-05eiri9jf9al5u4762shoudt6j99ldg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPersonalTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSAag9piuKENZDa3aex5hfs3zpcYMRUE',
    appId: '1:68816868203:ios:3dd6a5a40be4598ffe322e',
    messagingSenderId: '68816868203',
    projectId: 'my-personal-tasks-bb04d',
    storageBucket: 'my-personal-tasks-bb04d.appspot.com',
    iosClientId: '68816868203-05eiri9jf9al5u4762shoudt6j99ldg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPersonalTasks',
  );
}
